name: build
on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: 'Tag to build'
        required: true
      arch:
        type: choice
        description: 'Arch to build'
        required: true
        default: 'x86_64'
        options:
          - x86_64
          - arm64
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: mount sda1
        run: |
          sudo umount /mnt
          mkdir temp
          sudo mount /dev/sda1 temp
      - name: Show left space
        run: |
          df -H
          pwd
      - name: Get depot_tools
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          echo "$(pwd)/depot_tools" >> $GITHUB_PATH
          mkdir chromium
      - name: Pull code
        working-directory: chromium
        env:
          TAG: ${{ inputs.tag }}
        run: |
          echo 'solutions = [ { "name": "src", "url": "https://chromium.googlesource.com/chromium/src.git", "managed": False, "custom_deps": {}, "custom_vars": {}, }, ]' > .gclient
          mkdir src
          cd src
          git init
          echo 'start fetch'
          git fetch https://chromium.googlesource.com/chromium/src.git +refs/tags/$TAG:dummy --depth=1
          git checkout $TAG
          cd ..
          gclient sync
      - name: Install deps
        working-directory: chromium/src
        run: |
          ./build/install-build-deps.sh
          ./build/linux/sysroot_scripts/install-sysroot.py --arch=${{ inputs.arch }}
          gclient runhooks
          git fetch --tags
          git checkout ${{ inputs.tag }}
          gclient sync
          gn gen out --args='enable_nacl=false symbol_level=0 is_debug=false blink_symbol_level=0 v8_symbol_level=0 target_cpu="arm64"'
      - name: Build
        working-directory: chromium/src
        run: |
          mkdir out
          echo -e "enable_nacl=false\nis_debug=false\nsymbol_level=0\nblink_symbol_level=0\nv8_symbol_level=0\nis_official_build=true\ntarget_cpu=${{ inputs.arch }}" > out/args.gn
          gn gen out
          autoninja -C out chrome/installer/linux
