name: build
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to build'
        required: true
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get depot_tools
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          echo "$(pwd)/depot_tools" >> $GITHUB_PATH
          mkdir chromium
      - name: Pull code
        working-directory: chromium
        run: |
          fetch --nohooks chromium
      - name: Install deps
        working-directory: chromium/src
        run: |
          ./build/install-build-deps.sh
          ./build/linux/sysroot_scripts/install-sysroot.py --arch=arm
          gclient runhooks
          git fetch --tags
          git checkout ${{ inputs.tag }}
          gclient sync
          gn gen out --args='enable_nacl=false symbol_level=0 is_debug=false blink_symbol_level=0 v8_symbol_level=0 target_cpu="arm64"'
      - name: Show head and tag
        working-directory: chromium/src
        run: |
          git status
          git tags --list
          #      - name: Build
          #        working_directory: chromium/src
          #        run: |
          #          autoninja -C out chrome
