name: build
on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: 'Tag to build'
        required: true
      arch:
        type: choice
        description: 'Arch to build'
        required: true
        default: 'x64'
        options:
          - x64
          - x86
          - arm
          - arm64
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Delete swap and mount temp disk
        run: |
          lsblk
          sudo swapoff -a
          sudo rm -rf /mnt/*
          sudo umount /mnt
          mkdir temp
          sudo mount /dev/sda1 temp
          df -H
